export const QUESTIONS = [
  { id: 1, key: 'industry',    text: 'What industry does your company operate in?',                                       ph: 'e.g. Technology / SaaS, Healthcare, Retail, Finance…' },
  { id: 2, key: 'problem',     text: 'What problem does your company solve?',                                              ph: 'Describe the core problem your product addresses…' },
  { id: 3, key: 'customer',    text: 'Who is your primary target customer?',                                               ph: 'e.g. B2B enterprise, SMBs, mass market consumers…' },
  { id: 4, key: 'geo',         text: 'Which geographic markets does your company target?',                                  ph: 'e.g. North America, Europe, Asia-Pacific…' },
  { id: 5, key: 'tam',         text: 'What is your estimated Total Addressable Market (TAM)?',                             ph: 'e.g. $5B, around $500M, not sure yet…' },
  { id: 6, key: 'competitors', text: 'Who are your top 3 competitors? (comma-separated)',                                  ph: 'e.g. Salesforce, HubSpot, Zoho…' },
  { id: 7, key: 'pricing',     text: "What is your company's pricing model?",                                              ph: 'e.g. Subscription $49/mo, one-time purchase, freemium…' },
  { id: 8, key: 'price',       text: 'What is the average price of your product or service?',                             ph: 'e.g. $99/month, $499 one-time, free with premium at $29/mo…' },
  { id: 9, key: 'ratings',     text: 'How does your company compare to competitors? Describe your strengths and weaknesses.', ph: 'e.g. Our product quality is strong (5/5), pricing is competitive (4/5), but brand awareness is low (2/5)…' },
  { id: 10, key: 'sc',         text: 'What stage is your company in and what are your biggest market challenges?',         ph: 'e.g. Growth stage (Series A), biggest challenges are customer acquisition cost and intense competition…' },
];

export const CHART_COLORS = ['#1a2b5e','#2563eb','#60a5fa','#16a34a','#f59e0b','#ea580c'];

export const FALLBACK_DATA = {
  kpi: { tam:'$5.2B', growthRate:'8.5%', customers:'1.2M', competitors:6, stage:'Growth', price:'$45', stars:4 },
  growth: { labels:['2019','2020','2021','2022','2023','2024','2025'], values:[1,1.3,1.7,2.2,3.0,4.0,5.2] },
  segments: [{ label:'Enterprise',value:45 },{ label:'SMB',value:35 },{ label:'Startups',value:20 }],
  geo: [{ label:'North America',value:40 },{ label:'Europe',value:30 },{ label:'Asia',value:20 },{ label:'Others',value:10 }],
  competitors: [{ name:'Comp A',share:35 },{ name:'Comp B',share:25 },{ name:'Comp C',share:18 },{ name:'You',share:12 },{ name:'Others',share:10 }],
  radarLabels: ['Price','Product Quality','Brand Strength','Innovation','Customer Support'],
  radarYou: [3,4,3,4,4], radarComp: [4,3,4,3,3],
  sentiment: { positive:70, neutral:20, negative:10 },
  pricing: [{ name:'Your Product',color:'#16a34a',note:'Competitive' },{ name:'Comp A',color:'#1a2b5e',note:'Premium' },{ name:'Comp B',color:'#f59e0b',note:'Budget' }],
  avgRating: '4.3',
  challenges: ['Intense competition','Market awareness','CAC','Talent shortage'],
  insights: '🎯 Strong TAM with differentiation opportunity. 📈 Fragmented competition creates share capture potential. 💡 Customer support is your key differentiator — invest here.',
  detailedReport: {
    executiveSummary: '### 1.1 Market Environment & Overview\nThis comprehensive market research report provides an in-depth strategic analysis of the target industry, key demand drivers, and the competitive environment. The primary objective is to evaluate market opportunities, benchmark competitor strategies, and recommend actionable growth pathways. By examining macro-economic trends alongside granular consumer segments, this report aims to guide senior leadership in decision-making. Over the past decade, rapid technical developments have completely restructured standard operations, prompting a shift toward cloud-based architectures. As organizations face mounting pressure to optimize their workflows, understanding these structural market forces becomes a critical prerequisite for maintaining a competitive edge.\n\n### 1.2 Core Strategic Opportunity\nThe findings suggest a highly dynamic market landscape characterized by steady digital expansion and evolving user preferences. The subject company exhibits strong differentiation capabilities, particularly in product innovation and customer-centric support, which can be leveraged to capture market share from legacy providers. Strategic pricing adjustments and focused regional GTM campaigns will be essential to establish a sustainable competitive advantage. Incumbents are often slow to adapt to custom workflows, leaving a significant opening for agile, modular software solutions that prioritize integration flexibility and rapid deployment times.\n\n### 1.3 Strategic Positioning Matrix\nTo capitalize on these dynamics, the company must align its product roadmap with emerging user expectations. Developing robust integrations and keeping high-touch customer support channels will create a powerful customer retention loop. Additionally, building strong developer relations and self-service onboarding will bypass traditional enterprise sales friction and accelerate growth velocity. By focusing on customer-led growth strategies and expanding the partner ecosystem, the firm can establish a highly defensible market position that sustains long-term expansion.',
    marketGrowth: '### 2.1 Macroeconomic Demand Drivers\nBased on the historical and projected data, the market has demonstrated consistent upward momentum, expanding from early baselines to a projected size of $5.2B. This steady growth is driven by accelerated digital transformation, regulatory compliance frameworks, and increasing adoption rates across target demographics. Organizations in this space must capitalize on this trajectory by scaling operations to meet growing demand. Furthermore, the rising integration of cloud architectures has enabled real-time data processing, opening new avenues for product extension and strategic market positioning.\n\n### 2.2 Historical Analysis and CAGR Trends\nLooking forward, technological shifts such as machine learning integration and automated workflows are anticipated to accelerate demand. Over the next five years, the industry is poised to see a compound annual growth rate (CAGR) of over 8.5%, driven primarily by the transition from legacy on-premise systems to cloud-native platforms. Companies that innovate early will capture the lion\'s share of this expanding addressable market. Industry consolidation is also expected to increase, making early-stage agility a massive strategic differentiator.\n\n### 2.3 Future Projections & Industry Vectors\nIn addition to organic expansion, consolidation trends are reshaping provider concentration. Medium-sized firms are acquiring niche players to build integrated suites, while enterprise buyers increasingly prefer single-platform solutions over fragmented toolchains. Positioning the company as an all-in-one hub will capture this high-margin customer behavior. By investing in scalable infrastructure and robust API layers, the firm can future-proof its offerings against potential market disruptions.',
    segmentation: '### 3.1 Customer Demographics & Profiles\nThe market is divided into distinct customer segments: Enterprise accounts for the largest share at 45%, followed closely by SMBs at 35%, and Startups at 20%. The high concentration in Enterprise suggests significant contract value opportunities, while the SMB and Startup segments represent high-velocity growth areas that require lower touch-points and streamlined onboarding. Understanding the unique operational profiles of these segments is vital for maximizing sales conversions and GTM efficacy.\n\n### 3.2 Buying Behaviors and Purchasing Power\nTo effectively target these segments, product positioning must be tailored to their specific needs. Enterprise customers prioritize data security, custom integrations, and SLA compliance, and are willing to pay premium prices. Conversely, SMBs and Startups value ease of use, immediate time-to-value, and flexible subscription tiers. They are highly sensitive to initial setup friction, making intuitive user interfaces a primary conversion driver in self-service channels.\n\n### 3.3 Product Fit & Segment Capture\nWe recommend a dual-track sales model: a high-touch direct sales pipeline for complex enterprise deals, and a product-led self-service channel for SMBs. This minimizes customer acquisition friction and maximizes sales efficiency. By offering tailored modules, the company can address diverse client segments without diluting product focus. Ongoing user behavior analysis will help refine feature sets for each tier, ensuring high retention and product-led expansion.',
    geography: '### 4.1 Global Penetration & Market Shares\nGeographical breakdown indicates that North America leads market share at 40%, with Europe representing 30%, Asia at 20%, and other regions comprising the remaining 10%. Expansion efforts should prioritize strengthening presence in established North American and European markets before executing localized GTM strategies in fast-growing Asian hubs. Establishing local data centers and regional compliance teams will be essential for building customer trust in newly entered regions.\n\n### 4.2 Regulatory Influences & Compliance\nNorth American dominance is driven by early technology adoption and high IT budgets, making it the primary market for high-value contracts. Meanwhile, Europe presents growth opportunities fueled by stringent data privacy regulations (such as GDPR) that demand localized cloud hosting. Compliance will serve as a strong market barrier, locking out non-compliant players and creating a highly defensible niche for first-movers who invest in local certifications.\n\n### 4.3 Territorial Expansion Strategy\nEntering the Asia-Pacific region requires careful customization of product offerings to cater to localized language preferences and mobile-first users. Partnering with local resellers and distributors is highly recommended to accelerate time-to-market. Establishing local server nodes will also improve application latency and user experience, reducing churn rates and driving customer acquisition across key emerging hubs.',
    competition: '### 5.1 Player Concentration & Market Share\nThe competitive landscape features established players, with Competitor A leading at 35% market share, followed by Competitor B at 25%, and Competitor C at 18%. Your company currently commands a 12% share. According to the positioning matrix, your core differentiators lie in product innovation and customer support, whereas competitors leverage brand legacy and aggressive pricing. This fragmentation offers a prime opportunity for market entry and consolidation.\n\n### 5.2 Incumbent Vulnerability & Disruption\nTo bridge the gap with market leaders, the company must focus on customer acquisition efficiency and expanding partner ecosystems. Competitor A\'s dominant share indicates strong brand recall but also potential vulnerability to agile innovators offering more modern, cost-effective alternatives. Legacy platforms are frequently bogged down by technical debt, making them slower to deploy new capabilities.\n\n### 5.3 Strategic Differentiators\nBy positioning itself as a modern value leader, your company can systematically win over dissatisfied users from legacy platforms. Launching targeted migration tools and import scripts will minimize customer switching friction. Investing in brand marketing and public relations is essential to build trust and match legacy competitor credibility, ultimately accelerating GTM velocity and conversion rates.',
    radarAnalysis: '### 6.1 Capabilities Positioning Analysis\nA detailed evaluation of the competitive positioning matrix highlights key strategic vectors. While legacy competitors excel in brand strength and market reach due to their long history, they are often rated lower in product innovation and customer support responsiveness. This gap presents a significant window of opportunity for your company to differentiate itself and attract frustrated enterprise clients.\n\n### 6.2 Product Innovation & Support Scores\nYour company scores exceptionally well in innovation and customer support, reflecting a product-first culture and dedicated success teams. These scores reflect our agile development lifecycle and proactive account management models, which have yielded high customer satisfaction rates. Maintaining this edge requires continuous investment in R&D and customer success staffing.\n\n### 6.3 Strategic Capabilities Alignment\nHowever, brand awareness remains a critical bottleneck. Addressing this requires targeted marketing campaigns, customer advocacy programs, and social proof (such as case studies and industry badges) to match the perceived brand strength of established competitors. Co-marketing with key technology partners will also boost market trust and elevate industry visibility.',
    pricing: '### 7.1 Framework Evaluation & Price Sensitivity\nA comparative analysis of pricing structures shows a diverse range of models. While Competitor A occupies the premium tier, Competitor B captures budget-conscious users. Your product is positioned as a competitive value option, balancing advanced features with an accessible price point to maximize customer acquisition. Ongoing pricing sensitivity assessments will help optimize margins as the brand matures.\n\n### 7.2 Monetization Scaling & Tiers\nWe recommend adopting a value-based pricing model that scales with customer usage metrics (e.g., active users, API calls, or storage). This aligns the pricing structure with the value delivered, making it attractive for early-stage companies to start small while ensuring enterprise accounts scale to high-value tiers. Tiered pricing structures should remain transparent and easy to navigate.\n\n### 7.3 Long-term Value Extraction\nRegular reviews of price sensitivity should be conducted to capture margin improvements. Introducing add-on professional services or dedicated support packages for enterprise tiers can further expand contract values. Tiered packaging should be continually optimized to drive expansions and minimize contract downgrades, maximizing lifetime value.',
    risks: '### 8.1 Market Barriers & Structural Risks\nThe primary risks facing the company include intense competition from legacy vendors, high customer acquisition costs (CAC), and potential talent shortages in key engineering and product roles. Mitigating these challenges requires investing heavily in proprietary product features to raise switching costs and optimizing self-service customer pipelines. Proactive risk management is a key differentiator.\n\n### 8.2 Operational Risks & Vulnerabilities\nTo offset the threat of legacy incumbents, the company should focus on building deep integration ecosystems that make the product indispensable to the customer\'s daily workflow. Talent shortages can be addressed by establishing remote-friendly work policies and strong employer branding, attracting top talent globally.\n\n### 8.3 Mitigation Frameworks\nFinally, optimizing the digital onboarding flow will reduce dependency on high-touch sales teams, thus lowering CAC and accelerating growth. Implementing automated product tours and analytics will allow for data-driven product optimization and improve customer self-activation rates. Establishing a continuous feedback loop will further refine our operational agility.'
  }
};
