export const QUESTIONS = [
  { id: 1, key: 'industry',    text: 'What industry does your company operate in?',                                       ph: 'e.g. Technology / SaaS, Healthcare, Retail, Finance…' },
  { id: 2, key: 'problem',     text: 'What problem does your company solve?',                                              ph: 'Describe the core problem your product addresses…' },
  { id: 3, key: 'customer',    text: 'Who is your primary target customer?',                                               ph: 'e.g. B2B enterprise, SMBs, mass market consumers…' },
  { id: 4, key: 'geo',         text: 'Which geographic markets does your company target?',                                  ph: 'e.g. North America, Europe, Asia-Pacific…' },
  { id: 5, key: 'tam',         text: 'What is your estimated Total Addressable Market (TAM)?',                             ph: 'e.g. $5B, around $500M, not sure yet…' },
  { id: 6, key: 'competitors', text: 'Who are your top 3 competitors? (comma-separated)',                                  ph: 'e.g. Salesforce, HubSpot, Zoho…' },
  { id: 7, key: 'pricing',     text: "What is your company's pricing model?",                                              ph: 'e.g. Subscription $49/mo, one-time purchase, freemium…' },
  { id: 8, key: 'price',       text: 'What is the average price of your product or service?',                             ph: 'e.g. $99/month, $499 one-time, free with premium at $29/mo…' },
  { id: 9, key: 'ratings',     text: 'How does your company compare to competitors? Describe your strengths and weaknesses.', ph: 'e.g. Our product quality is strong (5/5), pricing is competitive (4/5), but brand awareness is low (2/5)…' },
  { id: 10, key: 'sc',         text: 'What stage is your company in and what are your biggest market challenges?',         ph: 'e.g. Growth stage (Series A), biggest challenges are customer acquisition cost and intense competition…' },
];

export const CHART_COLORS = ['#1a2b5e','#2563eb','#60a5fa','#16a34a','#f59e0b','#ea580c'];

export const FALLBACK_DATA = {
  kpi: { tam:'$5.2B', growthRate:'8.5%', customers:'1.2M', competitors:6, stage:'Growth', price:'$45', stars:4 },
  growth: { labels:['2019','2020','2021','2022','2023','2024','2025'], values:[1,1.3,1.7,2.2,3.0,4.0,5.2] },
  segments: [{ label:'Enterprise',value:45 },{ label:'SMB',value:35 },{ label:'Startups',value:20 }],
  geo: [{ label:'North America',value:40 },{ label:'Europe',value:30 },{ label:'Asia',value:20 },{ label:'Others',value:10 }],
  competitors: [{ name:'Comp A',share:35 },{ name:'Comp B',share:25 },{ name:'Comp C',share:18 },{ name:'You',share:12 },{ name:'Others',share:10 }],
  radarLabels: ['Price','Product Quality','Brand Strength','Innovation','Customer Support'],
  radarYou: [3,4,3,4,4], radarComp: [4,3,4,3,3],
  sentiment: { positive:70, neutral:20, negative:10 },
  pricing: [{ name:'Your Product',color:'#16a34a',note:'Competitive' },{ name:'Comp A',color:'#1a2b5e',note:'Premium' },{ name:'Comp B',color:'#f59e0b',note:'Budget' }],
  avgRating: '4.3',
  challenges: ['Intense competition','Market awareness','CAC','Talent shortage'],
  insights: '🎯 Strong TAM with differentiation opportunity. 📈 Fragmented competition creates share capture potential. 💡 Customer support is your key differentiator — invest here.',
  detailedReport: {
    executiveSummary: 'This comprehensive market research report provides an in-depth strategic analysis of the target industry, key demand drivers, and the competitive environment. The primary objective is to evaluate market opportunities, benchmark competitor strategies, and recommend actionable growth pathways. By examining macro-economic trends alongside granular consumer segments, this report aims to guide senior leadership in decision-making.\n\nThe findings suggest a highly dynamic market landscape characterized by steady digital expansion and evolving user preferences. The subject company exhibits strong differentiation capabilities, particularly in product innovation and customer-centric support, which can be leveraged to capture market share from legacy providers. Strategic pricing adjustments and focused regional GTM campaigns will be essential to establish a sustainable competitive advantage.',
    marketGrowth: 'Based on the historical and projected data, the market has demonstrated consistent upward momentum, expanding from early baselines to a projected size of $5.2B. This steady growth is driven by accelerated digital transformation, regulatory compliance frameworks, and increasing adoption rates across target demographics. Organizations in this space must capitalize on this trajectory by scaling operations to meet growing demand.\n\nLooking forward, technological shifts such as machine learning integration and automated workflows are anticipated to accelerate demand. Over the next five years, the industry is poised to see a compound annual growth rate (CAGR) of over 8.5%, driven primarily by the transition from legacy on-premise systems to cloud-native platforms. Companies that innovate early will capture the lion\'s share of this expanding addressable market.',
    segmentation: 'The market is divided into distinct customer segments: Enterprise accounts for the largest share at 45%, followed closely by SMBs at 35%, and Startups at 20%. The high concentration in Enterprise suggests significant contract value opportunities, while the SMB and Startup segments represent high-velocity growth areas that require lower touch-points and streamlined onboarding.\n\nTo effectively target these segments, product positioning must be tailored to their specific needs. Enterprise customers prioritize data security, custom integrations, and SLA compliance, and are willing to pay premium prices. Conversely, SMBs and Startups value ease of use, immediate time-to-value, and flexible subscription tiers. A multi-pronged GTM strategy will allow the company to capture value across the entire spectrum.',
    geography: 'Geographical breakdown indicates that North America leads market share at 40%, with Europe representing 30%, Asia at 20%, and other regions comprising the remaining 10%. Expansion efforts should prioritize strengthening presence in established North American and European markets before executing localized GTM strategies in fast-growing Asian hubs.\n\nNorth American dominance is driven by early technology adoption and high IT budgets, making it the primary market for high-value contracts. Meanwhile, Europe presents growth opportunities fueled by stringent data privacy regulations that demand localized cloud hosting. Entering the Asia-Pacific region requires careful customization of product offerings to cater to localized language preferences and mobile-first users.',
    competition: 'The competitive landscape features established players, with Competitor A leading at 35% market share, followed by Competitor B at 25%, and Competitor C at 18%. Your company currently commands a 12% share. According to the positioning matrix, your core differentiators lie in product innovation and customer support, whereas competitors leverage brand legacy and aggressive pricing.\n\nTo bridge the gap with market leaders, the company must focus on customer acquisition efficiency and expanding partner ecosystems. Competitor A\'s dominant share indicates strong brand recall but also potential vulnerability to agile innovators offering more modern, cost-effective alternatives. By positioning itself as a modern value leader, your company can systematically win over dissatisfied users from legacy platforms.',
    radarAnalysis: 'A detailed evaluation of the competitive positioning matrix highlights key strategic vectors. While legacy competitors excel in brand strength and market reach due to their long history, they are often rated lower in product innovation and customer support responsiveness. This gap presents a significant window of opportunity for your company to differentiate itself.\n\nYour company scores exceptionally well in innovation and customer support, reflecting a product-first culture and dedicated success teams. However, brand awareness remains a critical bottleneck. Addressing this requires targeted marketing campaigns, customer advocacy programs, and social proof (such as case studies and industry badges) to match the perceived brand strength of established competitors.',
    pricing: 'A comparative analysis of pricing structures shows a diverse range of models. While Competitor A occupies the premium tier, Competitor B captures budget-conscious users. Your product is positioned as a competitive value option, balancing advanced features with an accessible price point to maximize customer acquisition.\n\nWe recommend adopting a value-based pricing model that scales with customer usage metrics (e.g., active users, API calls, or storage). This aligns the pricing structure with the value delivered, making it attractive for early-stage companies to start small while ensuring enterprise accounts scale to high-value tiers. Regular reviews of price sensitivity should be conducted to capture margin improvements.',
    risks: 'The primary risks facing the company include intense competition from legacy vendors, high customer acquisition costs (CAC), and potential talent shortages in key engineering and product roles. Mitigating these challenges requires investing heavily in proprietary product features to raise switching costs and optimizing self-service customer pipelines.\n\nTo offset the threat of legacy incumbents, the company should focus on building deep integration ecosystems that make the product indispensable to the customer\'s daily workflow. Talent shortages can be addressed by establishing remote-friendly work policies and strong employer branding. Finally, optimizing the digital onboarding flow will reduce dependency on high-touch sales teams, thus lowering CAC and accelerating growth.'
  }
};
